generate_exe:
    image: mono:latest

    variables:
        rutaASln: ./Guarderia.sln
        rutaAProyecto: .

    before_script:
        - echo $rutaASln
        - nuget restore $rutaASln

    script:
        - msbuild /p:Configuration=Release $rutaASln
        - mkdir proyecto        
        - mv $rutaAProyecto/bin/Release/* proyecto
        - ls -al proyecto
    artifacts:
        paths:
          - proyecto
        expire_in: 3 hours
    when: manual
